name       : kshisen
version    : 19.12.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.0/src/kshisen-19.12.0.tar.xz : a650a45d0d614edd9a99b070b5edd642b6a6e2cc528fb74eb076b3a617bcfaab
homepage   : https://kde.org/applications/games/org.kde.kshisen
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : Shisen-Sho is a solitaire-like game played using the standard set of Mahjong tiles
description: |
    Shisen-Sho is a solitaire-like game played using the standard set of Mahjong tiles. Unlike Mahjong however, Shisen-Sho has only one layer of scrambled tiles.
    You can remove matching pieces if they can be connected with a line with at most two bends in it. At the same time, the line must not cross any other tiles.
    To win a game of Shisen-Sho the player has to remove all the tiles from the game board.
builddeps  :
    - extra-cmake-modules
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kxmlgui-devel
    - libkdegames-devel
    - libkmahjongg-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
