name       : kshisen
version    : 22.12.1
release    : 43
source     :
    - https://cdn.download.kde.org/stable/release-service/22.12.1/src/kshisen-22.12.1.tar.xz : 141a6a521e976c2e2a5e549b2ed31a319b1e11127d5d915a64ad3ce4f7771f5e
homepage   : https://kde.org/applications/games/org.kde.kshisen
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : Shisen-Sho is a solitaire-like game played using the standard set of Mahjong tiles
description: |
    Shisen-Sho is a solitaire-like game played using the standard set of Mahjong tiles. Unlike Mahjong however, Shisen-Sho has only one layer of scrambled tiles.
    You can remove matching pieces if they can be connected with a line with at most two bends in it. At the same time, the line must not cross any other tiles.
    To win a game of Shisen-Sho the player has to remove all the tiles from the game board.
builddeps  :
    - pkgconfig(Qt5Quick)
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kxmlgui-devel
    - libkdegames-devel
    - libkmahjongg-devel
rundeps    :
    - kmahjongg
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
