name       : kshisen
version    : 20.04.2
release    : 16
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.2/src/kshisen-20.04.2.tar.xz : ec21e1ceb57fb3f8d69fbf2350313f8d9e80b66e2537dcfce2ed39a23dcca4d2
homepage   : https://kde.org/applications/games/org.kde.kshisen
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : Shisen-Sho is a solitaire-like game played using the standard set of Mahjong tiles
description: |
    Shisen-Sho is a solitaire-like game played using the standard set of Mahjong tiles. Unlike Mahjong however, Shisen-Sho has only one layer of scrambled tiles.
    You can remove matching pieces if they can be connected with a line with at most two bends in it. At the same time, the line must not cross any other tiles.
    To win a game of Shisen-Sho the player has to remove all the tiles from the game board.
builddeps  :
    - extra-cmake-modules
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kxmlgui-devel
    - libkdegames-devel
    - libkmahjongg-devel
rundeps    :
    - kmahjongg
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
