name       : kshisen
version    : 20.12.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/kshisen-20.12.0.tar.xz : cb3dbf3c8dae6aa4ea1b591cc8e5964ff53e3e5e8d5b8aaedeb1c5191cc83cc3
homepage   : https://kde.org/applications/games/org.kde.kshisen
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : games.puzzle
summary    : Shisen-Sho is a solitaire-like game played using the standard set of Mahjong tiles
description: |
    Shisen-Sho is a solitaire-like game played using the standard set of Mahjong tiles. Unlike Mahjong however, Shisen-Sho has only one layer of scrambled tiles.
    You can remove matching pieces if they can be connected with a line with at most two bends in it. At the same time, the line must not cross any other tiles.
    To win a game of Shisen-Sho the player has to remove all the tiles from the game board.
builddeps  :
    - extra-cmake-modules
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kxmlgui-devel
    - libkdegames-devel
    - libkmahjongg-devel
rundeps    :
    - kmahjongg
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove doc
    rm -rf $installdir/usr/share/doc
